# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Base VM OS configuration.
  config.vm.box = "centos/7"
  config.ssh.insert_key = true
  # plugin
  config.hostmanager.enabled = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = true
  config.vbguest.auto_update = false

  # General VirtualBox VM configuration.
  config.vm.provider :virtualbox do |v|
    v.linked_clone = true
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # controller
  config.vm.define "devstack" do |node|
    node.vm.hostname = "devstack"
    config.vm.synced_folder '.', '/vagrant'
    node.vm.network :private_network, ip: "192.168.30.11"
    node.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 8192]
      v.customize ["modifyvm", :id, "--cpus", 4]
    end
  end
  config.vm.provision "shell", path: "run.sh"
  config.vm.provision "file", source: "local.conf", destination: "~/devstack/local.conf"
end
