# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Base VM OS configuration.
  #config.vm.box = "ubuntu/xenial64"
  config.vm.box = "sysop/ubuntu"
  config.ssh.username = "ubuntu"
  config.ssh.insert_key = true

  # General VirtualBox VM configuration.
  config.vm.provider :virtualbox do |v|
    v.memory = 8192
    v.cpus = 4
    v.linked_clone = true
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # kubeadm
  config.vm.define "kubeadm" do |kubeadm|
    kubeadm.vm.hostname = "kubeadm"
    kubeadm.vm.network :private_network, ip: "192.168.21.2"
  end
  
  # ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "main.yml"
    #ansible.sudo = true
  end
  
end
