# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Base VM OS configuration.
  config.vm.box = "sysop/ubuntu1604"
  config.ssh.username = "ubuntu"
  config.ssh.insert_key = true

  # General VirtualBox VM configuration.
  config.vm.provider :virtualbox do |v|
    v.memory = 1024 * 6
    v.cpus = 4
    v.linked_clone = true
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # vm
  config.vm.define "kubeadm" do |node|
    node.vm.hostname = "k8s-cont"
    node.vm.network :private_network, ip: "192.168.21.2"
  end
  
  # provisioner
  config.vm.provision "shell" do |node|
    node.inline = "apt install -y -q python-minimal python2.7"
  end
  config.vm.provision "ansible" do |node|
    node.playbook = "main.yml"
    #node.sudo = true
  end
  
end
