# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Base VM OS configuration.
  config.vm.box = "sysop/ubuntu1604"
  config.vm.synced_folder '~/github/kubespray', '/kubespray', owner: 'ubuntu', group: 'ubuntu'
  config.ssh.username = "ubuntu"
  config.ssh.insert_key = true
  # network
  config.vm.network "public_network",
    type: "dhcp",
    bridge: "enx0023579c3647",
    use_dhcp_assigned_default_route: true
  config.vm.provision "shell",
    run: "always",
    inline: "ip route del default && ip route add default dev enp0s8 via 192.168.1.254"
  # plugin
  config.hostmanager.enabled = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = true
  config.vbguest.auto_update = false

  # General VirtualBox VM configuration.
  config.vm.provider :virtualbox do |v|
    v.memory = 4096
    v.cpus = 4
    v.linked_clone = true
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # master
  config.vm.define "kube-master" do |node|
    node.vm.hostname = "kube-master"
    node.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 3072]
      v.customize ["modifyvm", :id, "--cpus", 2]
    end
    node.vm.provision "shell", :path => 'setup.sh', :args => 'master'
  end

  # node
  hosts = [
    { :name => "kube-node01", :ip => "192.168.21.21" },
    { :name => "kube-node02", :ip => "192.168.21.22" }
  ]

  hosts.each do |opts|
    config.vm.define opts[:name] do |node|
      node.vm.hostname = opts[:name]
      node.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--memory", 2048]
        v.customize ["modifyvm", :id, "--cpus", 2]
      end
      node.vm.provision "shell", :path => 'setup.sh', :args => 'node'
    end
  end

end
